### ISSUE TITLE
Build without  CVN functionality 

### ISSUE THREAD

**Issue by jsalatas** [FairChains/fairchains#4]
This is more a question than a bug. 

Do we really want to build the code without CVN? 

Code doesn't build (undefined reference) if you don't explicitly add the —with-cvn option in the configure script as by default it is off.

**Comment by thokon00** [comment]
CVN specific code doesn't hurt in a 'client only' setup. But it should definitely be possible to build without `--with-cvn` which renders this a bug.

`promptForPassword()` must not be defined conditionally in FairChains because `fairchain-tools` always uses it.
