### ISSUE TITLE
build error / protobuf undefined reference

### ISSUE THREAD

**Issue by TonyFord** [FairChains/fairchains#5]
I tried building fairchains-qt but it did not work. 
I tried different protoc versions / gcc versions but nothing works. Everytime the same error.

`
/usr/local/include/google/protobuf/arenastring.h:272: undefined reference to `google::protobuf::internal::fixed_address_empty_string[abi:cxx11]'
collect2: error: ld returned 1 exit status
Makefile:3896: die Regel für Ziel „qt/fairchains-qt“ scheiterte
make[2]: *** [qt/fairchains-qt] Fehler 1
`

**Comment by jsalatas** [comment]
> /usr/local/include/google .....

That shouldn't be in `/usr/local`. I just tested in a fresh ubuntu 16.04 installation and I managed to compile without issues, after doing the following
````
sudo add-apt-repository ppa:bitcoin/bitcoin
sudo apt update 
sudo apt install automake libtool build-essential libtool autotools-dev autoconf pkg-config libssl-dev libboost-all-dev libqt5gui5 libqt5core5a libqt5dbus5 qttools5-dev qttools5-dev-tools libprotobuf-dev protobuf-compiler libqrencode-dev autoconf openssl libssl-dev libevent-dev libminiupnpc-dev libzmq3-dev qtchooser libdb4.8-dev libdb4.8++-dev
````
notice the bitcoin ppa which provides the last two packages (`libdb4.8-dev` and `libdb4.8++-dev`). 

after that I was able to compile with the following options:

````
./configure --with-cvn --disable-tests --disable-bench 
````
my output for the above command in ubuntu 16.04 is available at: 

https://gist.github.com/jsalatas/3485be6ef8318712baaf88c20624e30d

**Comment by TonyFord** [comment]
Perfect, that's it.

The problem was the manual installation of protoc. In this case the protoc in the bitcoins ppa was ignored by the compiler.

I reinstalled the manual installation of protoc my `make uninstall` and reinstalled the protoc libraries by apt install. 

Now it works. Thx.
